name: Validate Pull Request

on: pull_request

jobs:
  deploy:
    name: Deploy to AWS
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: test
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_CERTIFICATE_ARN: ${{ secrets.AWS_CERTIFICATE_ARN }}

  e2e-tests:
    name: Run E2E Tests
    uses: ./.github/workflows/e2e-tests.yml
    permissions:
      contents: read
    with:
      environment: test
